name: Build

on:
  push: 
    branches: main

jobs:
  build-site:
    name: build gatsby site
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@5.12.2
      
      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public